insert into pre_forum_thread(
--  tid           , -- mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  fid           , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
  posttableid   , -- smallint(6) unsigned NOT NULL DEFAULT '0',
  typeid        , -- smallint(6) unsigned NOT NULL DEFAULT '0',
  sortid        , -- smallint(6) unsigned NOT NULL DEFAULT '0',
  readperm      , -- tinyint(3) unsigned NOT NULL DEFAULT '0',
  price         , -- smallint(6) NOT NULL DEFAULT '0',
  author        , -- char(15) NOT NULL DEFAULT '',
  authorid      , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
  `subject`     , -- char(80) NOT NULL DEFAULT '',
  dateline      , -- int(10) unsigned NOT NULL DEFAULT '0',
  lastpost      , -- int(10) unsigned NOT NULL DEFAULT '0',
  lastposter    , -- char(15) NOT NULL DEFAULT '',
  views         , -- int(10) unsigned NOT NULL DEFAULT '0',
  replies       , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
  displayorder  , -- tinyint(1) NOT NULL DEFAULT '0',
  highlight     , -- tinyint(1) NOT NULL DEFAULT '0',
  digest        , -- tinyint(1) NOT NULL DEFAULT '0',
  rate          , -- tinyint(1) NOT NULL DEFAULT '0',
  special       , -- tinyint(1) NOT NULL DEFAULT '0',
  attachment    , -- tinyint(1) NOT NULL DEFAULT '0',
  moderated     , -- tinyint(1) NOT NULL DEFAULT '0',
  closed        , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
  stickreply    , -- tinyint(1) unsigned NOT NULL DEFAULT '0',
  recommends    , -- smallint(6) NOT NULL DEFAULT '0',
  recommend_add , -- smallint(6) NOT NULL DEFAULT '0',
  recommend_sub , -- smallint(6) NOT NULL DEFAULT '0',
  heats         , -- int(10) unsigned NOT NULL DEFAULT '0',
  `status`      , -- smallint(6) unsigned NOT NULL DEFAULT '0',
  isgroup       , -- tinyint(1) NOT NULL DEFAULT '0',
  favtimes      , -- mediumint(8) NOT NULL DEFAULT '0',
  sharetimes    , -- mediumint(8) NOT NULL DEFAULT '0',
  stamp         , -- tinyint(3) NOT NULL DEFAULT '-1',
  icon          , -- tinyint(3) NOT NULL DEFAULT '-1',
  pushedaid     , -- mediumint(8) NOT NULL DEFAULT '0',
  cover         , -- smallint(6) NOT NULL DEFAULT '0',
  replycredit   , -- smallint(6) NOT NULL DEFAULT '0',
  relatebytag   , -- char(255) NOT NULL DEFAULT '0',
  maxposition   , -- int(8) unsigned NOT NULL DEFAULT '0',
  bgcolor       , -- char(8) NOT NULL DEFAULT '',
  comments      , -- int(10) unsigned NOT NULL DEFAULT '0',
  hidden        -- smallint(6) unsigned NOT NULL DEFAULT '0',
)
values(
1 /*fid           */,
0  /*posttableid   */,
0  /*typeid        */,
0  /*sortid        */,
0  /*readperm      */,
0  /*price         */,
'admin'  /*author        */,
1  /*authorid      */,
'new thread 1'  /*`subject`     */,
1478493031  /*dateline      */,
1478493031  /*lastpost      */,
'admin' /*lastposter    */,
0  /*views         */,
0  /*replies       */,
0  /*displayorder  */,
0  /*highlight     */,
0  /*digest        */,
0  /*rate          */,
0  /*special       */,
0  /*attachment    */,
0  /*moderated     */,
0  /*closed        */,
0  /*stickreply    */,
0  /*recommends    */,
0  /*recommend_add */,
0  /*recommend_sub */,
0  /*heats         */,
0  /*`status`      */,
0  /*isgroup       */,
0  /*favtimes      */,
0  /*sharetimes    */,
-1  /*stamp         */,
-1  /*icon          */,
0  /*pushedaid     */,
0  /*cover         */,
0  /*replycredit   */,
0  /*relatebytag   */,
1  /*maxposition   */,
''  /*bgcolor       */,
0  /*comments      */,
0  /*hidden        */
);
