-- insert into pre_forum_post_tableid(pid)values(2);

insert into pre_forum_post(
pid         , -- int(10) unsigned NOT NULL,
fid         , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
tid         , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
`first`     , -- tinyint(1) NOT NULL DEFAULT '0',
author      , -- varchar(15) NOT NULL DEFAULT '',
authorid    , -- mediumint(8) unsigned NOT NULL DEFAULT '0',
`subject`   , -- varchar(80) NOT NULL DEFAULT '',
dateline    , -- int(10) unsigned NOT NULL DEFAULT '0',
message     , -- mediumtext NOT NULL,
useip       , -- varchar(15) NOT NULL DEFAULT '',
`port`      , -- smallint(6) unsigned NOT NULL DEFAULT '0',
invisible   , -- tinyint(1) NOT NULL DEFAULT '0',
anonymous   , -- tinyint(1) NOT NULL DEFAULT '0',
usesig      , -- tinyint(1) NOT NULL DEFAULT '0',
htmlon      , -- tinyint(1) NOT NULL DEFAULT '0',
bbcodeoff   , -- tinyint(1) NOT NULL DEFAULT '0',
smileyoff   , -- tinyint(1) NOT NULL DEFAULT '0',
parseurloff , -- tinyint(1) NOT NULL DEFAULT '0',
attachment  , -- tinyint(1) NOT NULL DEFAULT '0',
rate        , -- smallint(6) NOT NULL DEFAULT '0',
ratetimes   , -- tinyint(3) unsigned NOT NULL DEFAULT '0',
`status`    , -- int(10) NOT NULL DEFAULT '0',
tags        , -- varchar(255) NOT NULL DEFAULT '0',
`comment`   , -- tinyint(1) NOT NULL DEFAULT '0',
replycredit   -- int(10) NOT NULL DEFAULT '0',
-- position    ,  int(8) unsigned NOT NULL AUTO_INCREMENT,
  )values
  (
4/*pid         */, 
1/*fid         */,  
2/*tid         */,   
0/*`first`     */, 
'admin'/*author      */, 
1/*authorid    */, 
''/*`subject`   */, 
1478493031/*dateline    */, 
'content 2'/*message     */, 
'192.168.1.1'/*useip       */, 
1234/*`port`      */, 
0/*invisible   */, 
0/*anonymous   */, 
0/*usesig      */, 
0/*htmlon      */, 
0/*bbcodeoff   */, 
0/*smileyoff   */, 
0/*parseurloff */, 
0/*attachment  */, 
0/*rate        */, 
0/*ratetimes   */, 
0/*`status`    */, 
0/*tags        */, 
0/*`comment`   */, 
0/*replycredit  */
);