DROP TABLE IF EXISTS ich_chess_manual
create table ich_chess_manual(
mid int(10) unsigned NOT NULL AUTO_INCREMENT,
ver  varchar(256) default '',
init varchar(256) default '',
pver varchar(256) default '',
viewurl varchar(256) default '',
adddate int(10) unsigned NOT NULL DEFAULT 0,
editdate int(10) unsigned NOT NULL DEFAULT 0,
title varchar(256) default '',
binit varchar(256) default '',
movelist text default '',
firstnum int default 0,
length int default 0,
type   varchar(64) default '',
gametype varchar(64) default '',
open varchar(64) default '',
class varchar(256) default '',
event varchar(256) default '',
group varchar(256) default '',
round varchar(256) default '',
table varchar(256) default '',
date int(10) unsigned NOT NULL DEFAULT 0,
place varchar(256) default '',
timerule varchar(256) default '',
red varchar(256) default '',
redteam varchar(256) default '',
redname varchar(256) default '',
redlevel varchar(256) default '',
redeng varchar(256) default '',
redrating varchar(256) default '',
redtime varchar(256) default '',
black varchar(256) default '',
blackteam varchar(256) default '',
blackname varchar(256) default '',
blacklevel varchar(256) default '',
blackeng varchar(256) default '',
blackrating varchar(256) default '',
blacktime varchar(256) default '',
result varchar(256) default '',
endtype varchar(256) default '',
judge varchar(256) default '',
record varchar(256) default '',
remark varchar(256) default '',
author varchar(256) default '',
refer varchar(256) default '',
other varchar(256) default '',
hits int default 0,
price int default 0,
sortid inde default 0,
owner varchar(256) default '',
oldowner varchar(256) default '',
hidden int default 0
)TYPE=MyISAM;